dependencies : 
  flutter :
    sdk :

  cupertino_icons : ^1.0.2
  image_picker : 0.8.4
  image_gallery_saver : 1.7.1
  uuid : 3.0.6

flutter : 
  uses-material-design : true

  assets : 
    - asset/img/