dependencies :
  flutter : 
    sdk : flutter
  
  cupertino_icons : ^1.0.2
  hive : 2.2.3
  hive_flutter : 1.1.0

dev_dependencies : 
  flutter_test : 
    sdk : flutter
  
  flutter_lints : 2.0.0
  hive_generator : 2.0.0
  build_runner : 2.3.2