dependencies :
  flutter :
    sdk : flutter
    
  cupertino_icons : ^1.0.2
  agora_rtc_engine : 6.0.0
  permission_handler : 10.0.2
  
flutter : 
  uses-material-design : true
  
  assets :
    - asset/img/