dependencies : 
  flutter : 
    sdk : flutter
    
  
  cupertino_icons : ^1.0.2
  image_picker : 0.8.5+3
  video_player : 2.4.6
  
flutter : 
  uses-material-design : true
  
  assets :
    - asset/img/